interface ${INTERFACE} {
    prefix ${PREFIX}/64 {
        AdvAutonomous on;
    };
    AdvManagedFlag on;
    MaxRtrAdvInterval 10;
    AdvDefaultLifetime 0;
    AdvDefaultPreference low;
    AdvSendAdvert on;
    IgnoreIfMissing on;
    AdvHomeAgentFlag off;
};
